<a href="https://colab.research.google.com/github/Caulhong/csgy-6923/blob/main/Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The SVM vs. Logistic Regression Showdown

In this lab, you will practice working with non-linear kernels combined with logistic regression and SVM classifiers. The goal is to compare these commonly used techniques. Which comes out on top in terms of accuracy? Runtime? Is there much of a difference at all? Is the dominance of the SVM classifier in machine learning pedagogy justified?

## Loading the Data

First, we load all the packages we'll need.

In [32]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics.pairwise import pairwise_kernels
import scipy
from sklearn import svm, linear_model
from sklearn.model_selection import GridSearchCV
import time


Again we download the data from the Tensorflow package, which you will need to install.  You can get the data from other sources as well.

In the Tensorflow dataset, the training and test data are represented as arrays:

     Xtr.shape = 60000 x 28 x 28
     Xts.shape = 10000 x 28 x 28
     
The test data consists of `60000` images of size `28 x 28` pixels; the test data consists of `10000` images.

In [33]:
import tensorflow as tf

(Xtr_raw,ytr),(Xts_raw,yts) = tf.keras.datasets.mnist.load_data()

print('Xtr shape: %s' % str(Xtr_raw.shape))
print('Xts shape: %s' % str(Xts_raw.shape))

ntr = Xtr_raw.shape[0]
nts = Xts_raw.shape[0]
nrow = Xtr_raw.shape[1]
ncol = Xtr_raw.shape[2]

Xtr shape: (60000, 28, 28)
Xts shape: (10000, 28, 28)


Each pixel value is from `[0,255]`.  For this lab, it will be convenient to recale the value to -1 to 1 and reshape it as a `ntr x npix` and `nts x npix`.

In [34]:
npix = nrow*ncol
Xtr = Xtr_raw.reshape((ntr,npix))
print(Xtr[1,:])
Xtr = (Xtr/255 - .5)
print(Xtr[1,:])

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0  51 159 253 159  50   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0  48 238 252 252 252 237   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0  54 227 253 252 239 233 252  57   6   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0  10  60 224 252 253 252 202  84 252
 253 122   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0 163 252 252 252 253 252 252  96 189 253 167   

In [35]:
npix = nrow*ncol
Xtr = (Xtr_raw/255 - 0.5)
Xtr = Xtr.reshape((ntr,npix))

Xts = (Xts_raw/255 - 0.5)
Xts = Xts.reshape((nts,npix))

In [36]:
print(Xtr)

[[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
 [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
 [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
 ...
 [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
 [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
 [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]


For this lab we're only going to use a fraction of the MNIST data -- otherwise our models will take too much time and memory to run. Using only part of the training data will of course lead to worse results. Given enough computational resources and time, we would ideally be running on the full data set. The follow code creates a new test and train set, with 10000 examples for train and 5000 for test.

In [37]:
ntr1 = 10000
nts1 = 5000
Iperm = np.random.permutation(ntr1)
Xtr1 = Xtr[Iperm[:ntr1],:]
ytr1 = ytr[Iperm[:ntr1]]
Iperm = np.random.permutation(nts1)
Xts1 = Xts[Iperm[:nts1],:]
yts1 = yts[Iperm[:nts1]]

## Problem set up and establishing a baseline

To simplify the problem (and speed things up) we're also going to restrict to binary classification. In particular, let's try to design classifier a that separates the 8's from all other digits.

Create binary 0/1 label vectors `ytr8` and `yts8` which are 1 wherever `ytr1` and `yts1` equal 8, and 0 everywhere else.

In [38]:
# TODO
# ytr8 =
# yts8 =
def convert_to_binary(labels):
    return np.where(labels == 8, 1, 0)
ytr8 = convert_to_binary(ytr1)
yts8 = convert_to_binary(yts1)

Most of the digits in the test dataset aren't equal to 8. So if we simply guess 0 for every image in `Xts`, we might expect to get classification accuracy around 90%. Our goal should be to significantly beat this **baseline**.

Formally, write a few lines of code to check what test error would be achieved by the all zeros classifier.

In [39]:
# TODO
# ...
# acc =
# print('Accuaracy = {0:f}'.format(acc))
num_zeros_yts8 = len(yts8) - np.sum(yts8)
num_correct_predictions = num_zeros_yts8
total_predictions = len(yts8)
acc = num_correct_predictions / total_predictions

print('Accuracy = {0:f}'.format(acc))

Accuracy = 0.902200


As a second baseline, let's see how we do with standard (non-kernel) logistic regression. As in the MNIST demo, you can use `scikit-learn`'s built in function `linear_model.LogisticRegression` to fit the model and compute the accuracy. Use no regularization and the `lbfgs` solver. You should acheive an improvement to around 93-95%.

In [40]:
# TODO
# ...
# acc =
# print('Logistic Regression Accuaracy = {0:f}'.format(acc))
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(penalty='none', solver='lbfgs')
logreg.fit(Xtr1, ytr8)
y_pred = logreg.predict(Xts1)
acc = (y_pred == yts8).mean()
print('Logistic Regression Accuracy = {0:f}'.format(acc))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1173: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(


Logistic Regression Accuracy = 0.940600


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## Kernel Logistic Regression

To improve on this baseline performance, let's try using the logistic regression classifier with a *non-linear* kernel. Recall from class that any non-linear kernel similarity function $k(\vec{w},\vec{z})$ is equal to $\phi(\vec{w})^T\phi(\vec{z})$ for some feature transformation $\phi$. However, we typically do not need to compute this feature tranformation explicitly: instead we can work directly with the kernel gram matrix $K \in \mathbb{R}^{n\times n}$. Recall that $K_{i,j} = k(\vec{x}_i,\vec{x}_j)$ where $\vec{x}_i$ is the $i^\text{th}$ training data point.

For this lab we will be using the radial basis function kernel. For a given scaling factor $\gamma$ this kernel is defined as:
$$
k(\vec{w},\vec{z}) = e^{-\gamma\|\vec{w}-\vec{z}\|_2^2}
$$

In [41]:
def rbf_kernel(w,z,gamma):
    d = w - z
    return np.exp(-gamma*np.sum(d*d))

Construct the kernel matrix `K1` for `Xtr1` with `gamma = .05`.

In [41]:
gamma = 0.05

# Compute the kernel matrix K1
n_tr1 = Xtr1.shape[0]
K1 = np.zeros((n_tr1, n_tr1))
for i in range(n_tr1):
    for j in range(n_tr1):
        K1[i, j] = rbf_kernel(Xtr1[i], Xtr1[j], gamma)

If you used a for loop (which is fine) your code might take several minutes to run! Part of the issue is that Python won't know to properly parallize your for loop. For this reason, when constructing kernel matrices it is often faster to us a built-in, carefully optimized function with explicit parallelization. Scikit learn provides such a function through their `metrics` library.

Referring to the documentation here
https://scikit-learn.org/stable/modules/metrics.html#metrics, use this built in function to recreate the same kernel matrix you did above. Store the result at `K`.

In [52]:
# TODO
# K =

from sklearn.metrics import pairwise_distances

gamma = 0.05

pairwise_sq_dist = pairwise_distances(Xtr1, metric='sqeuclidean')

K = np.exp(-gamma * pairwise_sq_dist)

Check that you used the function correctly by writing code to confirm that `K = K1`, or at least that the two are equal up to very small differences (which could arise due to numerical precision issues). Try to do this **without a for loop** for full credit. You will get partial credit if you use a for loop.

In [43]:
# TODO
are_equal = np.allclose(K, K1)

if are_equal:
    print("K and K1 are equal up to very small differences.")
else:
    print("K and K1 are not equal.")

K and K1 are equal up to very small differences.


When using a non-linear kernel, it is important to check that you have chosen reasonable parameters (in our case the only parameter is `gamma`). We typically do not want $k(\vec{x}_i,\vec{x}_j)$ to be either negligably small, or very large for all $i\neq j$ in our data set, or we won't be able to learn anything. For the RBF kernel this means that, for any $\vec{x}_i$ we don't want $k(\vec{x}_i,\vec{x}_j)$ very close to 1 (e.g. .9999) for all $j$, or very close to $0$ (e.g. 1e-8) for all $j$.

Let's just check that we're in good shape for the first data vector $\vec{x}_0$. Do so by printing out the 10 largest and 10 smallest values of $k(\vec{x}_0,\vec{x}_j)$ for $j\neq 0$. Note that we always have $k(\vec{x}_0,\vec{x}_0) = 1$ for the RBF kernel.

In [44]:
# TODO
# print('Maximum similarities: \n' + ...)
# print('Minimum similarities: \n' + ...)
similarities = K1[0, 1:]

sorted_indices = np.argsort(similarities)

print('Maximum similarities: \n' + str(similarities[sorted_indices[-10:]]))
print('Minimum similarities: \n' + str(similarities[sorted_indices[:10]]))

Maximum similarities: 
[0.77479048 0.77559936 0.7927614  0.80269654 0.83648434 0.8616145
 0.86425672 0.86883898 0.8702926  0.91601934]
Minimum similarities: 
[3.32180630e-05 3.49992552e-05 3.55790370e-05 4.01868789e-05
 4.29787030e-05 4.31194855e-05 5.29670344e-05 5.30306901e-05
 5.76715908e-05 5.81852148e-05]


### Implementation
Maybe surprisingly Scikit learn does not have an implementation for kernel logistic regression. So we have to implement our own!

Write a function function `log_fit` that minimizes the $\ell_2$-regularized logisitic regression loss:
$$
L(\boldsymbol{\alpha}) =\sum_{i=1}^n (1-y_i)(\phi(\mathbf{x}_i)^T\phi(\mathbf{X})^T\vec{\alpha}) - \log(h(\phi(\mathbf{x}_i)^T\phi(\mathbf{X})^T\boldsymbol{\alpha}) + \lambda \|\phi(\mathbf{X})^T\boldsymbol{\alpha}\|_2^2.
$$
As input it takes an $n\times n$ kernel matrix $K$ for the training data, an $n$ length vector `y` of binary class labels, and regularization parameter `lamb`.

To implement your function you can either use your own implmentation of gradient descent or used a built in minimizer from `scipy.optimize.minimize`. I recommend the later approach: as we saw in the last lab, gradient descent can converge slowly for this objective.

In [53]:
# TODO
# def log_fit(K,y,lamb,nit=1000):
#    Function which minizes the regularized logistic regression loss for a given kernel matrix K and target vector y
#    Return the optimal parameters alpha of the logisitic regression model.
from scipy.optimize import minimize

def logistic_loss(alpha, K, y, lamb):
    n = len(y)
    term1 = np.sum((1 - y) * (K @ alpha))
    term2 = np.sum(np.logaddexp(0, K @ alpha))
    term3 = lamb * alpha @ K @ alpha
    loss = term1 - term2 + term3
    return loss

def log_fit(K, y, lamb, nit=1):
    n = len(y)
    alpha_init = np.zeros(n)
    result = minimize(logistic_loss, alpha_init, args=(K, y, lamb), method='BFGS', options={'maxiter': nit})
    alpha_opt = result.x
    return alpha_opt

Use the `log_fit` function defined above to find parameters `alpha` for the kernel logistic regression model using `lamb = 0` and `K` as constructed above (with `gamma = .05`).

In [ ]:
# TODO
# alpha =
lamb = 0

alpha_opt = log_fit(K1, ytr8, lamb)

print("Optimal parameters alpha:", alpha_opt)

Suppose we have a test dataset with $m$ examples $\vec{w}_1,\ldots, \vec{w}_m$. Once we obtain a coefficient vector $\alpha$, making predictions for any $\vec{w}_j$ in the test set requires computing:
$$
{y}_{j} = \sum_{i=1}^n \alpha_i \cdot k(\vec{w}_{j}, \vec{x}_i).
$$
where $\vec{x}_1, \ldots \vec{x}_n$ are our training data vectors. We classify $\vec{w}_{j}$ in class 0 if ${y}_{j} \leq 0$ and in class 1 if ${y}_{j} > 0$.

This computation can be rewritten in matrix form as follows:
$$
\vec{y}_{test} = K_{test}\vec{\alpha},
$$
where $\vec{y}_{text}$ is an $m$ length vector and $K_{test}$ is a $m\times n$ matrix whose $(j,i)$ entry is equal to $k(\vec{w}_{j}, \vec{x}_i)$. We classify $\vec{w}_{j}$ in class 0 if $\vec{y}_{test}[j] \leq 0$ and in class 1 if $\vec{y}_{test}[j] > 0$.


Use the `pairwise_kernels` function to construct $K_{test}$. Then make predictions for the test set and evaluate the accuracy of our kernel logistic regression classifier. You should see a pretty substantial lift in accuracy to around $97\%$

In [15]:
# TODO
# Ktest = ...
Ktest = pairwise_kernels(Xts1, Xtr1, metric='rbf', gamma=gamma)

In [16]:
# TODO
# yhat = ... (vector containing predicted 0,1 labels)
# acc = np.mean(yhat == yts8)
# print("Test accuracy = %f" % acc)
yhat = Ktest @ alpha_opt

yhat_classes = (yhat > 0).astype(int)

acc = np.mean(yhat_classes == yts8)
print("Test accuracy = %f" % acc)

NameError: name 'alpha_opt' is not defined

## Kernel Support Vector Machine

The goal of this lab is to compare Kernel Logistic Regression to Kernel Support Vector machines. Following `demo_mnist_svm.ipynb` create and train an SVM classifier on `Xtr1` and `ytr8` using an RBF kernel with `gamma = .05` (the same value we used for logistic regression aboe). Use margin parameter `C = 10`.

In [46]:
# TODO

from sklearn.svm import SVC
svm_classifier = SVC(kernel='rbf', gamma=0.05, C=10)
svm_classifier.fit(Xtr1, ytr8)

SVC(C=10, gamma=0.05)

Calculate and print the accuracy of the SVM classifier. You should obtain a similar result as for logistic regression: something close to $97\%$ accuracy.

In [47]:
# TODO
# ysvm = ... (vector containing predicted 0,1 labels)
# acc = np.mean(yhat == yts8)
# print("Test accuracy = %f" % acc)
ysvm = svm_classifier.predict(Xts1)

acc = np.mean(ysvm == yts8)
print("Test accuracy = %f" % acc)

Test accuracy = 0.980200


## The Showdown

Both SVM classifiers and kernel logisitic regression require tuning parameters to obtain the best possible result. In our setting we will stick with an RBF kernel (although this could be tuned). So we only consider tuning the kernel width parameter `gamma`, as well as the regularization parameter `lamb` for logistic regression, and the margin parameter `C` for SVM. We will choose parameters using for-loops and train-test cross validation.

Train a logistic regression classifier with **all combinations** of the parameters included below in vectors `gamma` and `lamb`. For each setting of parameters, compute and print:
* the test error obtained
* the total runtime of classification in seconds (including training time and prediction time)

For computing runtime you might want to use the `time()` function from the `time` library, which we already imported ealier.

In [50]:
gamma_values = [.1, .05,.02,.01,.005]
lamb_values = [0,1e-6,1e-4,1e-2]
# TODO
# ...
from time import time
best_error = float('inf')
best_gamma = None
best_lamb = None
best_accuracy = None

for gamma in gamma_values:
    for lamb in lamb_values:
        start_time = time()
        Ktr = pairwise_kernels(Xtr1, metric='rbf', gamma=gamma)
        alpha_opt = log_fit(Ktr, ytr8, lamb)
        Ktest = pairwise_kernels(Xts1, Xtr1, metric='rbf', gamma=gamma)
        yhat = Ktest @ alpha_opt
        yhat_classes = (yhat > 0).astype(int)
        accuracy = np.mean(yhat_classes == yts8)
        test_error = 1 - accuracy
        runtime = time() - start_time
        print("Gamma: {:.4f}, Lambda: {:.6f}, Test Error: {:.4f}, Runtime: {:.4f} seconds".format(
            gamma, lamb, test_error, runtime))

        if test_error < best_error:
            best_error = test_error
            best_gamma = gamma
            best_lamb = lamb
            best_accuracy = accuracy

print("\nBest Parameters:")
print("Gamma: {:.4f}, Lambda: {:.6f}, Test Error: {:.4f}".format(best_gamma, best_lamb, best_error))
print("Best Test Accuracy: {:.4f}".format(best_accuracy))

TypeError: linear_kernel() got an unexpected keyword argument 'gamma'

TODO: What was the best test error achieved, and what setting of parameters achieved this error? Was the kernel logistic regression classifier more sensitive to changes in `gamma` or `lamb`? Discuss in 1-3 short sentences below.

Now let's do the same thing for the kernel Support Vector Classifier. Train an SVM classifier with **all combinations** of the parameters included below in vectors `gamma` and `C`. For each setting of parameters, compute:
* the test error obtained
* the total runtime of classification in seconds (including training time and prediction time)

In [48]:
from time import time

gamma_values = [0.1, 0.05, 0.02, 0.01, 0.005]
C_values = [0.01, 0.1, 1, 10]

best_error = float('inf')
best_gamma = None
best_C = None
best_accuracy = None

for gamma in gamma_values:
    for C in C_values:
        start_time = time()

        svm_classifier = SVC(kernel='rbf', gamma=gamma, C=C)
        svm_classifier.fit(Xtr1, ytr8)
        yhat = svm_classifier.predict(Xts1)
        accuracy = np.mean(yhat == yts8)
        test_error = 1 - accuracy
        runtime = time() - start_time
        print("Gamma: {:.4f}, C: {:.2f}, Test Error: {:.4f}, Runtime: {:.4f} seconds".format(
            gamma, C, test_error, runtime))
        if test_error < best_error:
            best_error = test_error
            best_gamma = gamma
            best_C = C
            best_accuracy = accuracy

print("\nBest Parameters:")
print("Gamma: {:.4f}, C: {:.2f}, Test Error: {:.4f}".format(best_gamma, best_C, best_error))
print("Best Test Accuracy: {:.4f}".format(best_accuracy))

Gamma: 0.1000, C: 0.01, Test Error: 0.0978, Runtime: 97.7690 seconds
Gamma: 0.1000, C: 0.10, Test Error: 0.0978, Runtime: 141.7715 seconds
Gamma: 0.1000, C: 1.00, Test Error: 0.0718, Runtime: 189.3415 seconds
Gamma: 0.1000, C: 10.00, Test Error: 0.0658, Runtime: 191.6527 seconds
Gamma: 0.0500, C: 0.01, Test Error: 0.0978, Runtime: 33.2527 seconds
Gamma: 0.0500, C: 0.10, Test Error: 0.0772, Runtime: 37.1832 seconds
Gamma: 0.0500, C: 1.00, Test Error: 0.0226, Runtime: 44.7030 seconds
Gamma: 0.0500, C: 10.00, Test Error: 0.0198, Runtime: 47.8005 seconds
Gamma: 0.0200, C: 0.01, Test Error: 0.0978, Runtime: 22.0348 seconds
Gamma: 0.0200, C: 0.10, Test Error: 0.0488, Runtime: 20.0954 seconds
Gamma: 0.0200, C: 1.00, Test Error: 0.0180, Runtime: 15.0502 seconds
Gamma: 0.0200, C: 10.00, Test Error: 0.0142, Runtime: 16.7805 seconds
Gamma: 0.0100, C: 0.01, Test Error: 0.0978, Runtime: 22.3982 seconds
Gamma: 0.0100, C: 0.10, Test Error: 0.0550, Runtime: 19.6158 seconds
Gamma: 0.0100, C: 1.00, Test

TODO: What was the best test error achieved, and what setting of parameters achieved this error? Which performed better in terms of accuracy, the SVM or logisitic regression classifier? How about in terms of runtime?

**NOTE:** For `sklearns`'s built in classifiers, including svm.SVC, there is a function called `GridSearchCV` which can automatically perform hyperparamater tuning for you. The main advantage of the method (as opposed to writing for-loops) is that it supports parallelization, so it can fit with different parameters at the same time. The function also supports automatic $k$-fold cross-validation (instead of simple train/test split).

You might be interested in using this function in the future. If so, please check out the tutorial in the following lab from previous year: https://github.com/sdrangan/introml/blob/master/unit08_svm/lab_emnist_partial.ipynb.